"""
app.services.telephony.twiml
────────────────────────────
TwiML response builders.

This file is intentionally tiny because ConversationRelay does the heavy
lifting now. Where v9 had ~700 lines of chunked-audio TwiML helpers,
v10 needs four:

  • connect_conversation_relay()  — the one TwiML we return on call
                                    answer; hands control to the
                                    websocket.
  • hangup()                      — fallback for error paths.
  • dial_transfer_number()        — for live-agent handoff after the
                                    websocket session ends.
  • transfer_failed()             — the polite "experts are busy"
                                    closer when a transfer doesn't
                                    connect.

Everything that used to be in here — chunk-by-chunk Play orchestration,
silence-prompt redirects, post-reply-action hooks — is GONE. The
websocket replaces all of it.
"""
from __future__ import annotations

from xml.sax.saxutils import escape, quoteattr

from app.core.config import get_settings


def _wrap(body: str) -> str:
    return f'<?xml version="1.0" encoding="UTF-8"?>\n<Response>\n{body}\n</Response>'


def _base_wss_url() -> str:
    """Derive the WSS URL of our own server from the configured base_url.

    base_url is set as e.g. https://your-app.onrender.com
    The websocket lives at wss://your-app.onrender.com/webhooks/twilio/cr
    """
    base = get_settings().base_url.rstrip("/")
    if base.startswith("https://"):
        return "wss://" + base[len("https://"):]
    if base.startswith("http://"):
        return "ws://" + base[len("http://"):]
    return base  # already protocol-prefixed or weird; let it through


def connect_conversation_relay(
    *,
    user_id: str,
    welcome_greeting: str,
    voice_id: str,
    tts_provider: str = "ElevenLabs",
    language: str = "en-US",
    transcription_provider: str = "Deepgram",
    speech_model: str = "nova-3-general",
    hints: str = "",
) -> str:
    """Build the <Connect><ConversationRelay> TwiML.

    Twilio fetches this on call-answer. The TwiML asks Twilio to:
      1. Open a websocket to our server at /webhooks/twilio/cr/{user_id}
         (the user_id in the path is how the websocket handler knows
         which tenant's settings to load — Twilio doesn't pass any
         auth on the websocket, only the call SID and customParameters).
      2. Use ElevenLabs for TTS with the user's chosen voice.
      3. Use Deepgram nova-3 for transcription (faster than Google, and
         the default for new accounts since Sept 2025).
      4. Speak the welcome_greeting immediately on connect — this is
         what the customer hears as the AI's opening line. Generated by
         the LLM at call-init time and passed through here so we don't
         need a separate /opening-audio endpoint.

    Notes on attributes:
      • interruptible="any" — customer can barge-in over the AI by
        speaking. Critical for natural conversation feel.
      • welcomeGreetingInterruptible="any" — they can also interrupt
        the opening line.
      • interruptSensitivity="medium" — high gives too many false barge-
        ins on noisy phone lines; low feels sluggish. Medium is the
        sweet spot per Twilio's own best-practice doc.
      • reportInputDuringAgentSpeech="speech" — we WANT to know when the
        customer is speaking even mid-AI-utterance, so we can cancel the
        in-flight LLM stream. (Default since May 2025 is "none", which
        means the AI keeps talking unaware. We override.)

    The custom <Parameter> elements forward the call's user_id and
    other tenant context to the websocket setup message — that's how
    the handler knows which user this call belongs to.
    """
    s = get_settings()
    ws_url = f"{_base_wss_url()}/webhooks/twilio/cr"

    # ConversationRelay attributes are XML attributes — they need
    # their values to be quoted-and-escaped properly. quoteattr handles
    # both the surrounding quotes and the escaping of any " inside.
    attrs_parts: list[str] = [
        f"url={quoteattr(ws_url)}",
        f"welcomeGreeting={quoteattr(welcome_greeting)}",
        f'welcomeGreetingInterruptible="any"',
        f"voice={quoteattr(voice_id)}",
        f"ttsProvider={quoteattr(tts_provider)}",
        f"language={quoteattr(language)}",
        f"transcriptionProvider={quoteattr(transcription_provider)}",
        f"speechModel={quoteattr(speech_model)}",
        f'interruptible="any"',
        f'interruptSensitivity="medium"',
        f'reportInputDuringAgentSpeech="speech"',
    ]
    if hints:
        attrs_parts.append(f"hints={quoteattr(hints)}")
    attrs = " ".join(attrs_parts)

    # We pass user_id as a custom <Parameter> so the websocket handler's
    # "setup" message has it. The path-only approach (?user_id=...) does
    # NOT work — Twilio strips query strings on websocket connect.
    # customParameters is the documented way to forward tenant data.
    parameter_lines = [
        f'    <Parameter name="user_id" value={quoteattr(user_id)} />',
    ]

    # Action URL fires after the <Connect> verb ends (websocket closed
    # OR session ended via end-message). We use it for the live-agent
    # handoff flow — when the AI emits [TRANSFER_CALL], we close the
    # websocket with handoffData saying "transfer to X", and Twilio
    # POSTs back to /webhooks/twilio/cr-action which dials the human.
    action_url = f"{s.base_url}/webhooks/twilio/cr-action"

    body = (
        f'  <Connect action="{escape(action_url)}" method="POST">\n'
        f"    <ConversationRelay {attrs}>\n"
        + "\n".join(parameter_lines) + "\n"
        f"    </ConversationRelay>\n"
        f"  </Connect>"
    )
    return _wrap(body)


def hangup() -> str:
    """End the call cleanly. Used as a fallback when something is wrong
    (unknown user, missing config, etc.) — better to hang up gracefully
    than to leave Twilio playing silence indefinitely."""
    return _wrap("  <Hangup/>")


def dial_transfer_number(number: str, sid: str, *, timeout: int = 25) -> str:
    """Dial a human teammate. Used when the AI signaled [TRANSFER_CALL].

    The action URL fires whether the dial succeeds or fails (DialCallStatus
    distinguishes them) so we can play the polite fallback if no one
    answered.
    """
    s = get_settings()
    action = f"{s.base_url}/webhooks/twilio/transfer-status?sid={escape(sid)}"
    return _wrap(
        f'  <Dial timeout="{timeout}" action="{escape(action)}" method="POST">\n'
        f"    {escape(number)}\n"
        f"  </Dial>"
    )


def transfer_failed(message: str) -> str:
    """Speak a polite closer when transfer didn't connect, then hang up.

    We use Twilio's built-in <Say> here rather than ElevenLabs because at
    this point the websocket session has already ended; we want a simple
    final TwiML that doesn't need the relay infrastructure. Twilio's
    Polly voice is acceptable for one short sentence.
    """
    return _wrap(
        f'  <Say voice="Polly.Joanna-Neural">{escape(message)}</Say>\n'
        f"  <Pause length=\"1\"/>\n"
        f"  <Hangup/>"
    )
